integrations:
  prometheus_remote_write:
    - basic_auth:
        password: eyJrIjoiMmRjN2M1MjU2YjY3Nzg4ZGZjOTdkMmJjYjc5NzBlZGQ5Mjg5NzY4NSIsIm4iOiJpMGVrMy1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTEyOTg3fQ==
        username: 143709
      url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
loki:
  configs:
    - clients:
        - basic_auth:
            password: eyJrIjoiMmRjN2M1MjU2YjY3Nzg4ZGZjOTdkMmJjYjc5NzBlZGQ5Mjg5NzY4NSIsIm4iOiJpMGVrMy1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTEyOTg3fQ==
            username: 70825
          url: https://logs-prod-us-central1.grafana.net/api/prom/push
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
prometheus:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: eyJrIjoiMmRjN2M1MjU2YjY3Nzg4ZGZjOTdkMmJjYjc5NzBlZGQ5Mjg5NzY4NSIsIm4iOiJpMGVrMy1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTEyOTg3fQ==
            username: 143709
          url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
      scrape_configs:
        - job_name: integrations/go
          static_configs:
            - targets:
                - localhost:8080
  global:
    scrape_interval: 15s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345
